# Generated by Django 4.0.6 on 2022-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instaworkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddata',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, '<em>Admin</em> | Can delete members'), (2, '<em>Regular</em> | Cannot delete members')], default=2),
        ),
    ]
