# Generated by Django 4.0.6 on 2022-07-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instaworkapp', '0003_alter_adddata_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
